/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import comboSearch.ComboSearch;
import controller.CatergoryControllerByChule;
import controller.ItemControllerByChule;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import models.Catergory;
import models.Item;
import validation.Validation;

/**
 *
 * @author Kanishka Gunarathna
 */
public class AddnewItem extends javax.swing.JPanel {

    /**
     * Creates new form AddnewItem
     */
    private ComboSearch getCategoryList;

    public AddnewItem() throws IOException {
        try {
            initComponents();
            getCategoryList = new ComboSearch();
            getCategoryList();
            ItemControllerByChule itemConyroller = new ItemControllerByChule();
            itemCodeText.setText(itemConyroller.getNewItemId());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "ClassNotFoundException occured." + "\n" + "ex.getMessage", null, JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SQLException occured. Please restart the system", null, JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        itemCodeText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        categoryCombo = new javax.swing.JComboBox();
        addButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        buyingPriceText = new javax.swing.JTextField();
        sellingPriceText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        qOHText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 36)); // NOI18N
        jLabel1.setText("Add New Item");

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel2.setText("Item Code   :");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel3.setText("Name          :");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel4.setText("Category     :");

        itemCodeText.setEditable(false);
        itemCodeText.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N

        nameText.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N

        categoryCombo.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        categoryCombo.setForeground(new java.awt.Color(51, 51, 255));

        addButton.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel5.setText("Buying Price:");

        buyingPriceText.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        buyingPriceText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buyingPriceTextKeyReleased(evt);
            }
        });

        sellingPriceText.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        sellingPriceText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sellingPriceTextKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel6.setText("Selling Price:");

        qOHText.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        qOHText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qOHTextFocusGained(evt);
            }
        });
        qOHText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qOHTextKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel7.setText("Qty On Hand:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buyingPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(sellingPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(itemCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(categoryCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(qOHText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 43, Short.MAX_VALUE))
                            .addComponent(jSeparator2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(itemCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(categoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qOHText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyingPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(sellingPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (!(itemCodeText.getText().isEmpty() || nameText.getText().trim().isEmpty() || qOHText.getText().isEmpty() || buyingPriceText.getText().isEmpty() || sellingPriceText.getText().isEmpty()) && categoryCombo.getSelectedIndex() != -1 && categoryCombo.getSelectedItem().toString().trim().split("<##>").length == 2) {
            StringTokenizer st=new StringTokenizer(nameText.getText().trim()); 
		int i=0;
		String token="";
		while(st.hasMoreTokens()){			
			token=st.nextToken("<##>");
			if((token!=null)&& !token.equals(nameText.getText().trim())){
				i++;
			}			
		}

            if (i == 0) {
                if ((buyingPriceText.getText().matches("[\\d]+[.]{1}[\\d]+") || buyingPriceText.getText().matches("[\\d]+")) && (sellingPriceText.getText().matches("[\\d]+[.]{1}[\\d]+") || sellingPriceText.getText().matches("[\\d]+")) && Integer.parseInt(qOHText.getText().trim()) > 0) {
                    String itemCode = itemCodeText.getText().trim();
                    String catergoryId = categoryCombo.getSelectedItem().toString().split("<##>")[1].trim();
                    String itemName = nameText.getText().trim();
                    int qtyOnHand = Integer.parseInt(qOHText.getText().trim());
                    double supplierPrice = Double.parseDouble(buyingPriceText.getText().trim());
                    double sellingprice = Double.parseDouble(sellingPriceText.getText().trim());

                    Item item = new Item(itemCode, catergoryId, itemName, qtyOnHand, supplierPrice, sellingprice);
                    ItemControllerByChule itemController = new ItemControllerByChule();
                    try {
                        int res = itemController.addItem(item);
                        if (res > 0) {
                            JOptionPane.showMessageDialog(this, "Item Added Successfully ");
                            setEmptyAll();
                        }
                    } catch (ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(null, "ClassNotFoundException occured." + "\n" + "ex.getMessage", null, JOptionPane.ERROR_MESSAGE);
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "SQLException occured. Please restart the system", null, JOptionPane.ERROR_MESSAGE);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "IOException occured." + "\n" + "ex.getMessage", null, JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please check buying and selling price or qtyOnHand", null, JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Some characters are not allowed for the itemName name", null, JOptionPane.ERROR_MESSAGE);
            }
        } else if (categoryCombo.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Please select a valid catergory", null, JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Please fill all fields", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void qOHTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qOHTextKeyReleased
        Validation.validateQty(qOHText);
    }//GEN-LAST:event_qOHTextKeyReleased

    private void buyingPriceTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buyingPriceTextKeyReleased
        Validation.validateprice(buyingPriceText);
    }//GEN-LAST:event_buyingPriceTextKeyReleased

    private void sellingPriceTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sellingPriceTextKeyReleased
        Validation.validateprice(sellingPriceText);
    }//GEN-LAST:event_sellingPriceTextKeyReleased

    private void qOHTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qOHTextFocusGained

    }//GEN-LAST:event_qOHTextFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField buyingPriceText;
    private javax.swing.JComboBox categoryCombo;
    private javax.swing.JTextField itemCodeText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField qOHText;
    private javax.swing.JTextField sellingPriceText;
    // End of variables declaration//GEN-END:variables

    private void getCategoryList() throws ClassNotFoundException, SQLException, IOException {
        CatergoryControllerByChule catergoryController = new CatergoryControllerByChule();
        ArrayList<Catergory> allCategories = catergoryController.getAllCatergories();
        categoryCombo.addItem("");
        for (Catergory category : allCategories) {
            categoryCombo.addItem(category.getCatergoryName() + "<##>" + category.getCategeryId());
        }
        getCategoryList.setSearchableCombo(categoryCombo, true, null);
    }

    private void setEmptyAll() throws ClassNotFoundException, SQLException, IOException {
        ItemControllerByChule itemConyroller = new ItemControllerByChule();
        itemCodeText.setText(itemConyroller.getNewItemId());
        nameText.setText(null);
        qOHText.setText(null);
        buyingPriceText.setText(null);
        sellingPriceText.setText(null);
        nameText.requestFocus();
        categoryCombo.setEnabled(true);
    }
}
