/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UserControllerByChule;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import models.User;
import validation.Validation;

/**
 *
 * @author Kanishka Gunarathna
 */
public class CreateUserAccount extends javax.swing.JPanel {

    /**
     * Creates new form CreateUserAccount
     */
    public CreateUserAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        confirmPassword = new javax.swing.JPasswordField();
        admin = new javax.swing.JRadioButton();
        limit = new javax.swing.JRadioButton();
        createButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabel1.setText("Create User Account");
        add(jLabel1);
        jLabel1.setBounds(238, 20, 336, 44);
        add(jSeparator1);
        jSeparator1.setBounds(10, 80, 827, 10);

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel2.setText("User Name               :");
        add(jLabel2);
        jLabel2.setBounds(110, 170, 176, 22);

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel3.setText("Password                  :");
        add(jLabel3);
        jLabel3.setBounds(110, 220, 177, 22);

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel4.setText("Confirm Password  :");
        add(jLabel4);
        jLabel4.setBounds(110, 270, 175, 22);

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel5.setText("Status                       :");
        add(jLabel5);
        jLabel5.setBounds(110, 130, 174, 22);

        messageLabel.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        messageLabel.setForeground(new java.awt.Color(204, 0, 0));
        add(messageLabel);
        messageLabel.setBounds(170, 320, 420, 40);

        userName.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        userName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userNameKeyReleased(evt);
            }
        });
        add(userName);
        userName.setBounds(290, 170, 399, 29);

        password.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        add(password);
        password.setBounds(290, 220, 279, 29);

        confirmPassword.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        confirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordActionPerformed(evt);
            }
        });
        add(confirmPassword);
        confirmPassword.setBounds(290, 260, 279, 29);

        buttonGroup1.add(admin);
        admin.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        admin.setText("   Admin");
        admin.setOpaque(false);
        add(admin);
        admin.setBounds(300, 130, 91, 31);

        buttonGroup1.add(limit);
        limit.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        limit.setSelected(true);
        limit.setText("   Limited");
        limit.setOpaque(false);
        add(limit);
        limit.setBounds(420, 130, 101, 31);

        createButton.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton);
        createButton.setBounds(600, 310, 91, 31);

        jButton2.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(700, 310, 91, 31);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fresh-green-background.jpg"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(0, 0, 860, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String type = "";
        if (admin.isSelected()) {
            type = "ADMINISTER";
        } else {
            type = "GUEST";;
        }
        StringTokenizer st = new StringTokenizer(userName.getText().trim());
        int i = 0;
        String token = "";
        while (st.hasMoreTokens()) {
            token = st.nextToken("<##>");
            if ((token != null) && !token.equals(userName.getText().trim())) {
                i++;
            }
        }
        try {
            if (!(userName.getText().isEmpty() || confirmPassword.getPassword().length == 0) && Arrays.equals(password.getPassword(), confirmPassword.getPassword()) && i == 0) {
                int addUser = UserControllerByChule.addUser(new User(userName.getText(), String.valueOf(confirmPassword.getPassword()), type));
                if (addUser > 0) {
                    JOptionPane.showMessageDialog(null, "User adding is successed", null, JOptionPane.INFORMATION_MESSAGE);
                    setNullAll();
                } else if (Arrays.equals(password.getPassword(), confirmPassword.getPassword())) {
                    messageLabel.setText("Password dosen't match");
                } else {
                    JOptionPane.showMessageDialog(null, "User adding is not successed", null, JOptionPane.ERROR_MESSAGE);
                }
            } else if (!Arrays.equals(password.getPassword(), confirmPassword.getPassword())) {
                messageLabel.setText("Password dosen't match");
            } else if (i != 0) {
                JOptionPane.showMessageDialog(null, "Some characters can't use for the user name", null, JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Please fill all fields", null, JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "ClassNotFoundException occured." + "\n" + "ex.getMessage", null, JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "This user already in the system", null, JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "IOException occured." + "\n" + "ex.getMessage", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        password.requestFocus();
    }//GEN-LAST:event_userNameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        confirmPassword.requestFocus();
    }//GEN-LAST:event_passwordActionPerformed

    private void confirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordActionPerformed
        if (password.getPassword().length != 0 && confirmPassword.getPassword().length != 0) {
            createButton.setEnabled(true);
            createButton.doClick();
        } else {
            JOptionPane.showMessageDialog(null, "Please fill all fields", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_confirmPasswordActionPerformed

    private void userNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameKeyReleased
        Validation.validateName(userName);
    }//GEN-LAST:event_userNameKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        userName.setText(null);
        password.setText(null);
        confirmPassword.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JButton createButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton limit;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
private void setNullAll() {
        userName.setText(null);
        password.setText(null);
        confirmPassword.setText(null);
    }

}
