/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import validation.Validation;

/**
 *
 * @author pavilion 15
 */
public class DiscountFrame extends javax.swing.JDialog {

    private NewOrderPenal panal;

    /**
     * Creates new form DiscountFrame
     */
    public DiscountFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        typeButtonGroup.add(presentageRButton);
        typeButtonGroup.add(amountRButton);
        amountRButton.setSelected(true);
        presentageField.setEnabled(false);
        if (amountRButton.isSelected()) {
            amountField.setEnabled(true);
            amountField.requestFocus();
            presentageField.setEnabled(false);
            amountField.setText(null);
            presentageField.setText(null);
        }
    }

    public DiscountFrame(java.awt.Frame parent, boolean modal, NewOrderPenal panal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        typeButtonGroup.add(presentageRButton);
        typeButtonGroup.add(amountRButton);
        amountRButton.setSelected(true);
        presentageField.setEnabled(false);

        amountField.setEnabled(true);
        amountField.setEditable(true);
        amountField.requestFocus();
        presentageField.setEnabled(false);
        amountField.setText(null);
        presentageField.setText(null);

        this.panal = panal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        amountRButton = new javax.swing.JRadioButton();
        presentageRButton = new javax.swing.JRadioButton();
        amountField = new javax.swing.JTextField();
        presentageField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 0, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose a discount type");
        jLabel1.setOpaque(true);

        amountRButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        amountRButton.setText("Amount");
        amountRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountRButtonActionPerformed(evt);
            }
        });
        amountRButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amountRButtonKeyPressed(evt);
            }
        });

        presentageRButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        presentageRButton.setText("Presentage");
        presentageRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentageRButtonActionPerformed(evt);
            }
        });
        presentageRButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                presentageRButtonKeyPressed(evt);
            }
        });

        amountField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });
        amountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amountFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountFieldKeyReleased(evt);
            }
        });

        presentageField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        presentageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentageFieldActionPerformed(evt);
            }
        });
        presentageField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                presentageFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                presentageFieldKeyReleased(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(6, 137, 6));
        addButton.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(presentageRButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(amountRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(presentageField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountRButton)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(presentageRButton)
                    .addComponent(presentageField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void presentageRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentageRButtonActionPerformed
        if (presentageRButton.isSelected()) {
            amountField.setEnabled(false);
            presentageField.setEnabled(true);
            presentageField.setEditable(true);
            amountField.setText(null);
            presentageField.setText(null);
        }
    }//GEN-LAST:event_presentageRButtonActionPerformed

    private void amountRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountRButtonActionPerformed
        if (amountRButton.isSelected()) {
            amountField.setEnabled(true);
            presentageField.setEnabled(false);
            amountField.setEditable(true);
            amountField.setText(null);
            presentageField.setText(null);
        }
    }//GEN-LAST:event_amountRButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (!amountField.getText().isEmpty() || !presentageField.getText().isEmpty()) {
            if (amountRButton.isSelected()) {
                if ((amountField.getText().trim().matches("[\\d]+[.]{1}[\\d]+") || amountField.getText().trim().matches("[\\d]+")) && Double.parseDouble(amountField.getText().trim()) <= Double.parseDouble(panal.totalAmount.getText().trim())) {
                    panal.discountAmount.setText(amountField.getText().trim());
                    panal.netTotalAmount.setText(String.valueOf((Double.parseDouble(panal.totalAmount.getText().trim()) - Double.parseDouble(amountField.getText().trim()) - Double.parseDouble(panal.creditAmount.getText().trim()))));
                    panal.discountCBox.setSelected(false);
                    panal.amount.requestFocus();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Please check discount amount", null, JOptionPane.ERROR_MESSAGE);
                }

            } else if (presentageRButton.isSelected()) {
                if ((Double.parseDouble(presentageField.getText().trim()) <= 100) && (presentageField.getText().trim().matches("[\\d]+[.]{1}[\\d]+") || presentageField.getText().trim().matches("[\\d]+"))) {
                    String discount = String.format("%1$.2f", ((Double.parseDouble(panal.totalAmount.getText().trim()) * Double.parseDouble(presentageField.getText().trim())) / 100));
                    panal.discountAmount.setText(discount);
                    panal.netTotalAmount.setText(String.valueOf((Double.parseDouble(panal.totalAmount.getText().trim()) - Double.parseDouble(panal.discountAmount.getText().trim()) - Double.parseDouble(panal.creditAmount.getText().trim()))));
                    panal.discountCBox.setSelected(false);
                    panal.amount.requestFocus();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid presentage", null, JOptionPane.ERROR_MESSAGE);
                    presentageField.setText(null);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "You must fill suitable field", null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        addButton.doClick();
    }//GEN-LAST:event_amountFieldActionPerformed

    private void presentageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentageFieldActionPerformed
        addButton.doClick();
    }//GEN-LAST:event_presentageFieldActionPerformed

    private void amountFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountFieldKeyReleased
        Validation.validateprice(amountField);
    }//GEN-LAST:event_amountFieldKeyReleased

    private void presentageFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_presentageFieldKeyReleased
        Validation.validateprice(presentageField);
    }//GEN-LAST:event_presentageFieldKeyReleased

    private void amountRButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountRButtonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            presentageRButton.setSelected(true);
        }
        if (presentageRButton.isSelected()) {
            amountField.setEnabled(false);
            presentageField.setEnabled(true);
            presentageField.setEditable(true);
            presentageField.requestFocus();
            amountField.setText(null);
            presentageField.setText(null);
        }
    }//GEN-LAST:event_amountRButtonKeyPressed

    private void presentageRButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_presentageRButtonKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            amountRButton.setSelected(true);
        }
        if (amountRButton.isSelected()) {
            amountField.setEnabled(true);
            amountField.setEditable(true);
            presentageField.setEnabled(false);
            amountField.requestFocus();
            amountField.setText(null);
            presentageField.setText(null);
        }

    }//GEN-LAST:event_presentageRButtonKeyPressed

    private void amountFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            presentageRButton.setSelected(true);
        }
        if (presentageRButton.isSelected()) {
            amountField.setEnabled(false);
            presentageField.setEnabled(true);
            presentageField.setEditable(true);
            presentageField.requestFocus();
            amountField.setText(null);
            presentageField.setText(null);
        }
    }//GEN-LAST:event_amountFieldKeyPressed

    private void presentageFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_presentageFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            amountRButton.setSelected(true);
        }
        if (amountRButton.isSelected()) {
            amountField.setEnabled(true);
            amountField.setEditable(true);
            presentageField.setEnabled(false);
            amountField.requestFocus();
            amountField.setText(null);
            presentageField.setText(null);
        }
    }//GEN-LAST:event_presentageFieldKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        panal.discountCBox.setSelected(false);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiscountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiscountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiscountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiscountFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiscountFrame dialog = new DiscountFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField amountField;
    private javax.swing.JRadioButton amountRButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField presentageField;
    private javax.swing.JRadioButton presentageRButton;
    private javax.swing.ButtonGroup typeButtonGroup;
    // End of variables declaration//GEN-END:variables
}
