/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Kanishka Gunarathna
 */
public class InfoPenal extends javax.swing.JPanel {

    /**
     * Creates new form InfoPenall
     */
    public InfoPenal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/TenaxLogo.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(43, 11, 157, 139);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 40)); // NOI18N
        jLabel1.setText("TENAXSOFT Production");
        add(jLabel1);
        jLabel1.setBounds(260, 30, 510, 43);
        add(jSeparator1);
        jSeparator1.setBounds(210, 80, 620, 10);

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Great innovations always behind us.......");
        add(jLabel3);
        jLabel3.setBounds(320, 100, 422, 30);

        jLabel4.setFont(new java.awt.Font("Schadow BT", 0, 20)); // NOI18N
        jLabel4.setText("A. Chulakshana Iushan Silva");
        add(jLabel4);
        jLabel4.setBounds(20, 190, 250, 26);

        jLabel5.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel5.setText("Chairman/Software Engineer/BA");
        add(jLabel5);
        jLabel5.setBounds(20, 220, 270, 24);

        jLabel6.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel6.setText("irushantenaxsotf2015@gmail.com");
        add(jLabel6);
        jLabel6.setBounds(20, 250, 269, 24);

        jLabel7.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel7.setText("0717333631");
        add(jLabel7);
        jLabel7.setBounds(20, 280, 100, 24);

        jLabel8.setFont(new java.awt.Font("NewsGoth Lt BT", 1, 24)); // NOI18N
        jLabel8.setText("tenaxsoft@gmail.com");
        add(jLabel8);
        jLabel8.setBounds(220, 510, 248, 32);

        jLabel9.setFont(new java.awt.Font("Schadow BT", 0, 20)); // NOI18N
        jLabel9.setText("Kanisha Henry Gunarathna");
        add(jLabel9);
        jLabel9.setBounds(600, 190, 240, 26);

        jLabel10.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel10.setText("UI Engineer / Software Engineer");
        add(jLabel10);
        jLabel10.setBounds(410, 370, 257, 24);

        jLabel11.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel11.setText("kanishkatenaxsotf2015@gmail.com");
        add(jLabel11);
        jLabel11.setBounds(600, 250, 281, 24);

        jLabel12.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel12.setText("0774945473");
        add(jLabel12);
        jLabel12.setBounds(600, 280, 100, 24);

        jLabel13.setFont(new java.awt.Font("Schadow BT", 0, 20)); // NOI18N
        jLabel13.setText("Ruchira Kalhara Mahaliyana");
        add(jLabel13);
        jLabel13.setBounds(310, 190, 250, 26);

        jLabel14.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel14.setText("Architec");
        add(jLabel14);
        jLabel14.setBounds(310, 220, 64, 24);

        jLabel15.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel15.setText("ruchiratenaxsotf2015@gmail.com");
        add(jLabel15);
        jLabel15.setBounds(310, 250, 265, 24);

        jLabel16.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel16.setText("0770425753");
        add(jLabel16);
        jLabel16.setBounds(310, 280, 100, 24);

        jLabel17.setFont(new java.awt.Font("Schadow BT", 0, 20)); // NOI18N
        jLabel17.setText("R.P. Kulangani Shermaila Rathnaweera ");
        add(jLabel17);
        jLabel17.setBounds(20, 340, 360, 26);

        jLabel18.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel18.setText("Accountant / Software Engineer");
        add(jLabel18);
        jLabel18.setBounds(20, 370, 252, 24);

        jLabel19.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel19.setText("kulanganitenaxsotf2015@gmail.com");
        add(jLabel19);
        jLabel19.setBounds(20, 400, 287, 24);

        jLabel20.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel20.setText("0789815173");
        add(jLabel20);
        jLabel20.setBounds(20, 430, 100, 24);

        jLabel21.setFont(new java.awt.Font("Schadow BT", 0, 20)); // NOI18N
        jLabel21.setText("W.V. Dilan Madusanka");
        add(jLabel21);
        jLabel21.setBounds(410, 340, 200, 26);

        jLabel23.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel23.setText("dilantenaxsotf2015@gmail.com");
        add(jLabel23);
        jLabel23.setBounds(410, 400, 248, 24);

        jLabel24.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel24.setText("0786384398");
        add(jLabel24);
        jLabel24.setBounds(410, 430, 100, 24);

        jLabel22.setFont(new java.awt.Font("Schadow BT", 0, 18)); // NOI18N
        jLabel22.setText("UI Engineer / Graphic Designer");
        add(jLabel22);
        jLabel22.setBounds(600, 220, 249, 24);

        jLabel25.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        jLabel25.setText("2015.09.15");
        add(jLabel25);
        jLabel25.setBounds(510, 510, 132, 29);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/infoPenalBacgroundpng.png"))); // NOI18N
        add(jLabel26);
        jLabel26.setBounds(0, 0, 890, 570);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
