/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CatergoryControllerByDilan;
import controller.ItemControllerByDilan;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Item;

/**
 *
 * @author Kanishka Gunarathna
 */
public class ViewStockPenal extends javax.swing.JPanel {

    /**
     * Creates new form ViewStockPenal
     */
    public DefaultTableModel tableModel = new DefaultTableModel();

    public ViewStockPenal() {
        initComponents();
        tableModel = (DefaultTableModel) allItemTable.getModel();
        allItemBtn.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allItemTable = new javax.swing.JTable();
        allItemBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jPanel2.setLayout(null);

        allItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Category", "Buying Price", "Selling Price", "Qty On Hand"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(allItemTable);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 67, 690, 465);

        allItemBtn.setBackground(new java.awt.Color(153, 255, 153));
        allItemBtn.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        allItemBtn.setText("All Items");
        allItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allItemBtnActionPerformed(evt);
            }
        });
        jPanel2.add(allItemBtn);
        allItemBtn.setBounds(10, 11, 331, 45);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jButton2.setText("Buffered Items");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(370, 11, 330, 45);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Jb6iCptqqqq.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 710, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void allItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allItemBtnActionPerformed
        tableModel.setRowCount(0);
        ItemControllerByDilan itemController = new ItemControllerByDilan();
        CatergoryControllerByDilan catergoryController = new CatergoryControllerByDilan();
        try {
            ArrayList<Item> allItemList = itemController.getAllItems();
            for (Item allItemList1 : allItemList) {
                Object[] item = {allItemList1.getItemCode(), allItemList1.getItemName(), catergoryController.searchCatergory(allItemList1.getCatergoryId()).getCatergoryName(),allItemList1.getSupplierPrice(),allItemList1.getSellingprice(), String.valueOf(allItemList1.getQtyOnHand())};
                tableModel.addRow(item);
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "ClassNotFoundException occured."+"\n"+"ex.getMessage", null, JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SQLException occured. Please restart the system", null, JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "IOException occured."+"\n"+"ex.getMessage", null, JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_allItemBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tableModel.setRowCount(0);
        ItemControllerByDilan itemController = new ItemControllerByDilan();
        CatergoryControllerByDilan catergoryController = new CatergoryControllerByDilan();
        try {
            String qty = JOptionPane.showInputDialog(null, "Please enter the qty", null, JOptionPane.INFORMATION_MESSAGE);            
            
            if (qty != null && qty.length() > 0&&qty.matches("[\\d]*")) {
                ArrayList<Item> allItemList = itemController.getAllItemsFiltered(Integer.parseInt(qty));
                for (Item allItemList1 : allItemList) {
                    Object[] item = {allItemList1.getItemCode(), allItemList1.getItemName(), catergoryController.searchCatergory(allItemList1.getCatergoryId()).getCatergoryName(),allItemList1.getSupplierPrice(),allItemList1.getSellingprice(), String.valueOf(allItemList1.getQtyOnHand())};
                    tableModel.addRow(item);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please enter a valid amount", null, JOptionPane.ERROR_MESSAGE);
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "ClassNotFoundException occured."+"\n"+"ex.getMessage", null, JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "SQLException occured. Please restart the system", null, JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "IOException occured."+"\n"+"ex.getMessage", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allItemBtn;
    private javax.swing.JTable allItemTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
